/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jingleheimercalendar;

import javax.swing.SwingUtilities;

/**
 *
 * @author Brandon
 */
public class CreateTaskPanel extends javax.swing.JPanel {
    javax.swing.JPanel parentContainer;
    
    DayPanel dayPanelRef;
    /**
     * Creates new form NewTaskPanel
     */
    public CreateTaskPanel(javax.swing.JPanel addHere, DayPanel d) {
        parentContainer = addHere;
        dayPanelRef = d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        createTask = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        taskName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskDetails = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priorityBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        completionDate = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 200));

        jPanel1.setBackground(new java.awt.Color(69, 69, 69));

        jLabel1.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        jLabel1.setText("Create A New Task");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(600, 4));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        createTask.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        createTask.setText("Create Task");
        createTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTaskActionPerformed(evt);
            }
        });
        cancel.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        taskName.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        taskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameActionPerformed(evt);
            }
        });

        taskDetails.setColumns(20);
        taskDetails.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        taskDetails.setRows(5);
        taskDetails.setText("(Optional)");
        jScrollPane1.setViewportView(taskDetails);

        jLabel2.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        jLabel2.setText("Task Name:");

        jLabel3.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        jLabel3.setText("Details:");

        priorityBox.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        priorityBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "! ! !", "! !", "!" }));
        priorityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        jLabel4.setText("Priority:");

        categoryBox.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        JingleheimerCalendar f = (JingleheimerCalendar) SwingUtilities.getWindowAncestor(parentContainer);
        String[] categoriesArray = new String[UserCalendar.getInstance().getCategories().size()];
       
        for(int i = 0;i< UserCalendar.getInstance().getCategories().size();i++){
           categoriesArray[i] = UserCalendar.getInstance().getCategories().get(i).getName();
        }
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel(categoriesArray));
        categoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        jLabel5.setText("Category:");

        jLabel6.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        jLabel6.setText("Completion Date (Optional) :");

        completionDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        completionDate.setText("MM/DD/YY");
        completionDate.setFont(JingleheimerCalendar.defaultFont.deriveFont(13f));
        completionDate.setPreferredSize(new java.awt.Dimension(119, 28));
        completionDate.setSize(new java.awt.Dimension(105, 28));
        completionDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completionDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priorityBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(completionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taskName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createTask, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)))
                .addGap(13, 13, 13))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createTask)
                            .addComponent(cancel))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(priorityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(completionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 170, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>                        

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        //AKA CANCEL
        /*if(tasks.isEmpty()){
            JPanel centerPanel = new JPanel(); 
            centerPanel.setLayout(new BorderLayout());
            centerPanel.setBackground(Color.WHITE);
            javax.swing.JLabel noEventMessage = new javax.swing.JLabel("No Task to Complete.");
            noEventMessage.setFont(new java.awt.Font("Helvetica Neue", 0, 12));
            noEventMessage.setHorizontalAlignment(SwingConstants.CENTER);
            centerPanel.add(noEventMessage, BorderLayout.CENTER); 

            parentContainer.add(centerPanel);
        }*/
        dayPanelRef.refreshTaskPanel();
        parentContainer.remove(this);
        parentContainer.validate();    
    }                                      

    private void taskNameActionPerformed(java.awt.event.ActionEvent evt) { 
    
    }
    private void createTaskActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        String name;
        String details;
        String cDate;
        Category category;
        int urgency;
        
        
        
            name = taskName.getText();
            details = taskDetails.getText();
            
            category = UserCalendar.getInstance().getCategories().get(categoryBox.getSelectedIndex());
          
            urgency = priorityBox.getSelectedIndex();
            cDate = completionDate.getText();
        
        if(details.equals("(Optional)")){
           details = "No Details Available For This Task";
        }
        if(cDate.equals("MM/DD/YY")){
           cDate = "N/A";
        }
        Task newTask = new Task(name,details,(3 - urgency),category, cDate);
        UserCalendar.getInstance().addTasks(newTask);
        
        dayPanelRef.refreshTaskPanel();
        parentContainer.remove(this);
        parentContainer.validate(); 
    }                                        

    private void priorityBoxActionPerformed(java.awt.event.ActionEvent evt) {                                            
       /* if(categoryBox.getSelectedIndex() == 0){
           jLabel4.setForeground(new  Color(204, 0, 0));
        }else if(categoryBox.getSelectedIndex() == 1){
           jLabel4.setForeground(new  Color(255,204,0));
        }else if(categoryBox.getSelectedIndex() == 2){
           jLabel4.setForeground(new  Color(102,204,0));
        }else{
           jLabel4.setForeground(new  Color(0,0,0));
        }  */
        
    }                                           

    private void categoryBoxActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
            jPanel1.setBackground(UserCalendar.getInstance().getCategories().get(categoryBox.getSelectedIndex()).getCategoryColor());
          
        
    }                                           

    private void completionDateActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }   
    
    


    // Variables declaration - do not modify                     
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox categoryBox;
    private javax.swing.JFormattedTextField completionDate;
    private javax.swing.JButton createTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox priorityBox;
    private javax.swing.JTextArea taskDetails;
    private javax.swing.JTextField taskName;
    // End of variables declaration         
}