package jingleheimercalendar;

import java.awt.Color;

/**
 *
 * @author Brandon
 */
public class CreateEventPanel extends javax.swing.JPanel{
    javax.swing.JPanel parentContainer;
    java.util.ArrayList<EventPanel> events;
    /**
     * Creates new form NewEventPanel
     */
    public CreateEventPanel(javax.swing.JPanel addHere, java.util.ArrayList<EventPanel> e) {
        parentContainer = addHere;
        events = e;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eventName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventNote = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scheduleEvent = new javax.swing.JButton();
        allDayEvent = new javax.swing.JCheckBox();
        categoryBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sTimeHour = new javax.swing.JComboBox();
        sTimeMin = new javax.swing.JComboBox();
        sTimeAP = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        eTimeAP = new javax.swing.JComboBox();
        eTimeMin = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        eTimeHour = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 225));

        eventName.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        eventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameActionPerformed(evt);
            }
        });

        eventNote.setColumns(20);
        eventNote.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        eventNote.setRows(5);
        eventNote.setText("(Optional)");
        jScrollPane1.setViewportView(eventNote);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel1.setText("Event Name:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel2.setText("Note:");

        scheduleEvent.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        scheduleEvent.setText("Schedule My Event");
        scheduleEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleEventActionPerformed(evt);
            }
        });

        allDayEvent.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        allDayEvent.setText("All Day Event");
        allDayEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDayEventActionPerformed(evt);
            }
        });

        categoryBox.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Category", "Category 1", "Category 2", "Category 3" }));
        categoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel3.setText("Category:");

        startTimeLabel.setBackground(new java.awt.Color(204, 204, 204));
        startTimeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        startTimeLabel.setText("Start Time:");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel5.setText("End Time:");

        sTimeHour.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        sTimeHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        sTimeMin.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        sTimeMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));
        sTimeMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTimeMinActionPerformed(evt);
            }
        });

        sTimeAP.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        sTimeAP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "am", "pm", " " }));

        jLabel8.setText(":");

        eTimeAP.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        eTimeAP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "am", "pm" }));

        eTimeMin.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        eTimeMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        jLabel10.setText(":");

        eTimeHour.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        eTimeHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel4.setText("Create A New Event ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(44, 44, 44)
                                                                .addComponent(jLabel2)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane1)
                                                        .addComponent(eventName)))
                                        .addComponent(allDayEvent))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(sTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel8)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(sTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sTimeAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(startTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(scheduleEvent)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addComponent(eTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(0, 0, 0)
                                                                        .addComponent(jLabel10)
                                                                        .addGap(0, 0, 0)
                                                                        .addComponent(eTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(eTimeAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(startTimeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(sTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(sTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(sTimeAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(eTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(eTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(eTimeAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel10))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(allDayEvent)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(scheduleEvent)
                                                        .addComponent(jButton1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>


    private void scheduleEventActionPerformed(java.awt.event.ActionEvent evt) {

        String startTime;
        String endTime;
        String name;
        String note;
        int categoryNum;

        if(allDayEvent.isSelected()){
            startTime = "All Day";
            endTime = "";
            name = eventName.getText();
            note = eventNote.getText();
            categoryNum = findCategory(categoryBox.getSelectedIndex());
        }else{
            startTime = sTimeHour.getSelectedItem().toString()+":"+sTimeMin.getSelectedItem().toString()+" "+sTimeAP.getSelectedItem().toString();
            endTime = eTimeHour.getSelectedItem().toString()+":"+eTimeMin.getSelectedItem().toString()+" "+eTimeAP.getSelectedItem().toString();
            name = eventName.getText();
            note = eventNote.getText();
            categoryNum = findCategory(categoryBox.getSelectedIndex());
        }
        if(note.equals("(Optional)")){
            note = "No Note Available For This Event";
        }
        EventPanel e = new EventPanel(startTime,endTime,name,note,categoryNum);

        events.add(e);

        if(events.indexOf(e)%2==0){
            e.setBackground(new Color(255,255,255));
        }else{
            e.setBackground(new Color(245,245,245));
        }

        parentContainer.add(e);
        parentContainer.remove(this);
        parentContainer.validate();

    }



    private void allDayEventActionPerformed(java.awt.event.ActionEvent evt) {
        eTimeHour.setEnabled(! eTimeHour.isEnabled());
        eTimeMin.setEnabled(! eTimeMin.isEnabled());
        eTimeAP.setEnabled(! eTimeAP.isEnabled());
        sTimeHour.setEnabled(! sTimeHour.isEnabled());
        sTimeMin.setEnabled(! sTimeMin.isEnabled());
        sTimeAP.setEnabled(! sTimeAP.isEnabled());
    }
    private int findCategory(int i){
        return new java.util.Random().nextInt(16777215);
    }
    private void eventNameActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void categoryBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if(categoryBox.getSelectedIndex() == 0){
            jPanel2.setBackground(new  Color(153,153,153));
        }else{
            jPanel2.setBackground(new Color(findCategory(categoryBox.getSelectedIndex())));
        }
    }

    private void sTimeMinActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void  jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        //AKA CANCEL
        parentContainer.remove(this);
        parentContainer.validate();
    }



    // Variables declaration - do not modify
    private javax.swing.JCheckBox allDayEvent;
    private javax.swing.JComboBox categoryBox;
    private javax.swing.JComboBox eTimeAP;
    private javax.swing.JComboBox eTimeHour;
    private javax.swing.JComboBox eTimeMin;
    private javax.swing.JTextField eventName;
    private javax.swing.JTextArea eventNote;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox sTimeAP;
    private javax.swing.JComboBox sTimeHour;
    private javax.swing.JComboBox sTimeMin;
    private javax.swing.JButton scheduleEvent;
    private javax.swing.JLabel startTimeLabel;
    // End of variables declaration
}
